import Head from "next/head";
import styles from "../styles/Home.module.css";
import Axiostest from "../components/Axiostest";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Axiostest />
    </div>
  );
};
export default Home;
